# Все сообщения в формате MiniMessage - https://webui.advntr.dev/
FlyPrefix: "<#ff9d4d>[<#b3ff26>FlyAway<#ff9d4d>]"
FlyOff: "<#ff4524>Режим полёта выключен"
FlyNoPermission: "<#ff4524>У вас нет прав"
FlyOn: "<#21ff30>Режим полёта включён"
# Настройки элитры (Все сообщения в формате MiniMessage - https://webui.advntr.dev/)
ElytraFlyOff: "<#21ff30>Вы сняли элитру и полёт был отключён"
NoElytra: "<#57ffe9>На вас не надета элитра, поэтому вы не можете включить полёт"

# Права
# flyaway.use - Использование команды /fly
# flyaway.bypass - Обход ограничение на элитры (т.е. для включения флая необязательно носить элитры)
# flyaway.elytra - Отключение флая если игрок снимает элитры
#